pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -e -X -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                sh 'chmod +x -R ${env.WORKSPACE}'
            }
        }
    }
}
